#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct  8 12:28:48 2017

accReturn累積報酬率 = 賺得錢/投入成本


@author: shawn
"""

def AnnualizedReturn(accReturn,year):
    sol = ((1.0+accReturn)**(1.0/year))-1.0
    return sol
